# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
- binary: gotherm
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  goarm:
    - 6
    - 7
    - 8
archives:
  - id: gothermostat
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    files:
      - README.md
      - LICENSE.md
      - web/build/**/*
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: marcofranssen
    name: gothermostat

nfpms:
  - id: gothermostat

    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    replacements:
      amd64: 64-bit
      darwin: macOS

    vendor: Marco Franssen
    homepage: https://marcofranssen.nl/

    maintainer: Marco Franssen <marco.franssen@gmail.com>
    description: Nest integration to fetch temperature changes.
    license: MIT

    formats:
      - deb

    dependencies: []
    recommends: []
    suggests: []
    conflicts: []

    # Override default /usr/local/bin destination for binaries
    # bindir: /opt/marcofranssen/gothermostat/bin

    epoch: 1

    empty_folders:
      - /var/log/marcofranssen/gothermostat
      - /etc/marcofranssen/gothermostat/data

    files:
      "scripts/etc/systemd/system/gothermostat.service": "/etc/systemd/system/gothermostat.service"
      "web/build/**/*": "/etc/marcofranssen/gothermostat/web/build"

    config_files:
      ".gotherm.toml.dist": "/etc/marcofranssen/gothermostat/.gotherm.toml"

    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"
      # postremove: "scripts/postremove.sh"

    overrides:
      deb:
        replacements:
          amd64: amd64

dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    skip_push: true
    dockerfile: Dockerfile
    image_templates:
      - "marcofranssen/gothermostat:latest"
      - "marcofranssen/gothermostat:{{ .Tag }}"
      - "marcofranssen/gothermostat:v{{ .Major }}"
      - "marcofranssen/gothermostat:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      - "--label=nl.marcofranssen.version={{.Version}}"
      - "--label=nl.marcofranssen.name={{.ProjectName}}"
      - "--build-arg=GIT_TAG={{.Tag}}"
      - "--build-arg=GIT_COMMIT={{.ShortCommit}}"
      - "--build-arg=RDATE={{.Date}}"
    binaries:
      - gotherm
    extra_files:
      - .gotherm.toml
