stages:
  - build
  - release

jobs:
  include:
    - stage: build
      language: node_js
      node_js: '12'
      cache:
        directories:
          - web/node_modules
      before_install:
        - cd web/
      install:
        - npm install
      script:
        - npm run test:coverage
        - npm run build
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      language: go
      go: 1.12.x
      before_install:
        - go get -t -v ./...
      script:
        - go test -race -coverprofile=coverage.out -covermode=atomic ./...
      install:
        - go get github.com/smartystreets/goconvey/convey
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: release
      language: go
      go: 1.12.x
      before_install:
        - go get -t -v ./...
      deploy: &github
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux
